name: apt-mirror
version: 0.5.4
summary: A tool to mirror apt repos
description: |
    A small tool that provides ability to mirror any parts (or
    even all) of Debian and Ubuntu GNU/Linux distributions or any other
    apt sources which typically provided by open source developers.

base: core22
grade: stable
confinement: strict

environment:
  PERL5LIB: ${SNAP}/usr/share/perl/5.34.0:${PERL5LIB}
  LANG: C

parts:
  apt-mirror:
    plugin: make
    source: https://github.com/apt-mirror/apt-mirror.git
    source-tag: "0.5.4"
    override-stage:
      snapcraftctl stage
      cp etc/mirror.list ${SNAP_DATA}/mirror.list
    stage-packages:
      - perl-modules
      - wget

apps:
  apt-mirror:
    command: usr/local/bin/apt-mirror /var/snap/apt-mirror/common/mirror.list
